# Config file for lithology classification
# Prompt file and version
prompts_file: bedrock/uscs_classification_prompts.yml
prompt_version: v7

# Pattern file and parameter version
pattern_file: bedrock/uscs_classification_patterns_bedrock.yml
pattern_version: baseline

# temperature - answer creativity for the LLM model
temperature: 0.0

# Maximum response tokens
max_tokens: 2048

# Parameter indicating if Reasoning (Chain of Thought) mode should be used. Warning this significantly increases latency
reasoning_mode: False

# Async params
max_concurrent_calls: 3
api_call_delay: 0.0
max_retries: 10
base_retry_delay: 0.3
max_delay: 30.0