baseline:
  en:
    lbo: "large boulder"
    bo: "boulder"
    co: "cobbles"
    gr: "gravel"
    cgr: "coarse gravel"
    mcgr: "medium-coarse gravel"
    mgr: "medium gravel"
    fmgr: "fine-medium gravel"
    fgr: "fine gravel"
    sa: "sand"
    csa: "coarse sand"
    mcsa: "medium-coarse sand"
    msa: "medium sand"
    fmsa: "fine-medium sand"
    fsa: "fine sand"
    si: "silt"
    cl: "clay"
    pt: "peat"
    or_: "organic soil"
    hu: "humus"
    an: "anthropogenic soil"
    ba: "backfill"
    oth: "other"
    ns: "not specified"

  de:
    lbo: "Grossblock"
    bo: "Block"
    co: "Steine"
    gr: "Kies"
    cgr: "Grobkies"
    mcgr: "Mittel-Grobkies"
    mgr: "Mittelkies"
    fmgr: "Fein-Mittelkies"
    fgr: "Feinkies"
    sa: "Sand"
    csa: "Grobsand"
    mcsa: "Mittel-Grobsand"
    msa: "Mittelsand"
    fmsa: "Fein-Mittelsand"
    fsa: "Feinsand"
    si: "Silt"
    cl: "Ton"
    pt: "Torf"
    or_: "Organischer Boden"
    hu: "Humus"
    an: "Anthropogener Boden"
    ba: "Auff√ºllung"
    oth: "anderer"
    ns: "keine Angabe"

  fr:
    lbo: "bloc grand"
    bo: "bloc"
    co: "galets"
    gr: "gravier"
    cgr: "gravier grossier"
    mcgr: "gravier moyen-grossier"
    mgr: "gravier moyen"
    fmgr: "gravier fin-moyen"
    fgr: "gravier fin"
    sa: "sable"
    csa: "sable grossier"
    mcsa: "sable moyen-grossier"
    msa: "sable moyen"
    fmsa: "sable fin-moyen"
    fsa: "sable fin"
    si: "limon"
    cl: "argile"
    pt: "tourbe"
    or_: "sol organique"
    hu: "humus"
    an: "sol anthropique"
    ba: "remblai"
    oth: "autre"
    ns: "sans indication"

  it:
    lbo: "masso grande"
    bo: "masso"
    co: "ciottoli"
    gr: "ghiaia"
    cgr: "ghiaia grossa"
    mcgr: "ghiaia media-grossa"
    mgr: "ghiaia media"
    fmgr: "ghiaia fine-media"
    fgr: "ghiaia fine"
    sa: "sabbia"
    csa: "sabbia grossa"
    mcsa: "sabbia media-grossa"
    msa: "sabbia media"
    fmsa: "sabbia fine-media"
    fsa: "sabbia fine"
    si: "limo"
    cl: "argilla"
    pt: "torba"
    or_: "suolo organico"
    hu: "humus"
    an: "suolo antropico"
    ba: "rinterro"
    oth: "altro"
    ns: "senza indicazioni"
