baseline:
  de:
    lbo: "grossblockig / mit Grossblöcken"
    bo: "blockig / mit Blöcken"
    co: "steinig / mit Steinen"
    gr: "kiesig"
    fgr: "feinkiesig"
    fmgr: "fein- bis mittelkiesig"
    mgr: "mittelkiesig"
    mcgr: "mittel- bis grobkiesig"
    cgr: "grobkiesig"
    sa: "sandig"
    fsa: "feinsandig"
    fmsa: "fein- bis mittelsandig"
    msa: "mittelsandig"
    mcsa: "mittel- bis grobsandig"
    csa: "grobsandig"
    si: "siltig"
    cl: "tonig"
    or_: "organische Beimengung"
    oth: "anderer"
    ns: "keine Angabe"

  fr:
    lbo: "avec gros blocs"
    bo: "bloqué / avec blocs"
    co: "pierreux / avec pierres"
    gr: "graveleux"
    fgr: "graveleux fin"
    fmgr: "graveleux fin à moyen"
    mgr: "graveleux moyen"
    mcgr: "graveleux moyen à grossier"
    cgr: "graveleux grossier"
    sa: "sableux"
    fsa: "sableux fin"
    fmsa: "sableux fin à moyen"
    msa: "sableux moyen"
    mcsa: "sableux moyen à grossier"
    csa: "sableux grossier"
    si: "limoneux"
    cl: "argileux"
    or_: "avec inclusion organique"
    oth: "autre"
    ns: "sans indication"

  it:
    lbo: "con grossi blocchi"
    bo: "con blocchi"
    co: "sassoso / con pietre"
    gr: "ghiaioso"
    fgr: "ghiaioso fine"
    fmgr: "ghiaioso fine-media"
    mgr: "ghiaioso medio"
    mcgr: "ghiaioso medio-grosso"
    cgr: "ghiaioso grosso"
    sa: "sabbioso"
    fsa: "sabbioso fine"
    fmsa: "sabbioso fine-media"
    msa: "sabbioso medio"
    mcsa: "sabbioso medio-grosso"
    csa: "sabbioso grosso"
    si: "limoso"
    cl: "argilloso"
    or_: "con inclusione organica"
    oth: "altro"
    ns: "senza indicazioni"

  en:
    lbo: "coarse blocky / with large blocks"
    bo: "blocky / with blocks"
    co: "stony / with stones"
    gr: "gravelly"
    fgr: "fine gravelly"
    fmgr: "fine to medium gravelly"
    mgr: "medium gravelly"
    mcgr: "medium to coarse gravelly"
    cgr: "coarse gravelly"
    sa: "sandy"
    fsa: "fine sandy"
    fmsa: "fine to medium sandy"
    msa: "medium sandy"
    mcsa: "medium to coarse sandy"
    csa: "coarse sandy"
    si: "silty"
    cl: "clayey"
    or_: "with organic inclusion"
    oth: "other"
    ns: "not specified"
