# Default parameters used for the borehole name detection pipeline, used as part of the swissgeol_doc_processing package.
# These paramaters should be changed only if we want to impact the functionality of the package globally.

# Overlap threshold for closest next line detection.
min_vertical_overlap: 0.9
# Max allowed distance between keyword and next line
max_horizontal_distance: 50
max_title_length: 10

# Keyword for borehole name detection
matching_keywords: [
    "baggerschacht",
    "baggerschlitz",
    "bohrstelle",
    "forage",
    "kernbohrung",
    "probenahmestelle",
    "rammkernbohrung",
    "rammsondierung",
    "rotationsbohrung",
    "rotationskernbohrung",
    "schachtprofil",
    "sondierbohrung",
    "sondierschacht",
    "sondage",
    "tranchée",
    "bohrung",
    "schacht",
    "sondierung",
]

# Keyword to ignore in borehole name detection
excluded_keywords: ["nr.", "nr", "n r", "n°", "nº", "no", "nummer"]