dummy:
  uscs: null
  lithology: null
  EN_main: null
baseline:
  uscs: baseline/baseline_config_uscs.yml
  lithology: baseline/baseline_config_lithology.yml
  EN_main: null
bert:
  uscs: bert/bert_config_uscs.yml
  lithology: bert/bert_config_lithology.yml
  EN_main: bert/bert_config_en_main.yml
bedrock:
  default: bedrock/bedrock_config_default.yml
  uscs: bedrock/bedrock_config_uscs.yml
  lithology: bedrock/bedrock_config_lithology.yml
  EN_main: bedrock/bedrock_config_en_main.yml
