dummy:
  uscs: null
  lithology: null
baseline:
  uscs: baseline/baseline_config_uscs.yml
  lithology: baseline/baseline_config_lithology.yml
bert:
  uscs: bert/bert_config_uscs.yml
  lithology: bert/bert_config_lithology.yml
bedrock:
  uscs: bedrock/bedrock_config_uscs.yml
  lithology: bedrock/bedrock_config_lithology.yml
